### ISSUE TITLE
16 Character 2 Line Parallel LCD Works

### ISSUE THREAD

**Issue by Eddiiie** [marcrdavis/ArduinoTITO-PlayerTracking#1]
Nice work on this!

Just wanted to say I was able to use this program using a 2 line 16 character LCD display by changing 2 lines in the code.
The 2 lines are obvious -  the include line and creating the object line.    There is one or two messages that don't fit in 16 characters (when it shows connected to the network) but that is a status message that appears for a few moments at startup.

Commented out the `#include  <IeeFlipNoFrills.h>` line replaced it with
`#include <LiquidCrystal.h>`

Crating the object was a little bit trickier.  The LCD uses the upper 4 bits for data.  Had to look up the datasheet and made it work with the liquidcrystal example "HelloWorld" first.   Once that sketch worked, it was easy to paste the lines (that's why it has a "const int " assigning all the pins. ; I copy/pasted it out of the HelloWorld sketch -

This is the same display that is in the Sentinel 1 Player Tracking panel, also explained here - [http://newlifegames.com/nlg/index.php?topic=28771.0](http://newlifegames.com/nlg/index.php?topic=28771.0)

```
//IeeFlipNoFrills vfd(22, 23, /*control pins */
//                    31, 30, 29, 28, 27, 26, 25, 24 /*data pins */);

const int rs = 22, en = 23, d4 = 27, d5 = 26, d6 = 25, d7 = 24;
LiquidCrystal vfd(rs, en, d4, d5, d6, d7);

````

All of this and I2C pins are still open, right?    ...   Mastercom!

**Comment by marcrdavis** [comment]
HI – Thanks!

 

I had this working on an LCD during the prototyping phase – besides the include there should only have needed minor changes to showMessageOnVFD and ScrollText functions, plus the size of your display as you noted. Most of those LCDs work in 4 bit mode so yes – that is a change. The other pins would be unused.

 

Marc
