### ISSUE TITLE
Unable to TITO

### ISSUE THREAD

**Issue by Eddiiie** [marcrdavis/ArduinoTITO-PlayerTracking#2]
I must be doing something wrong.

IGT G20, Mars BV

I have BettorTITO working.   Removed it, connected The ArduinoTITO-PlayerTracking System.   Followed the great instructions, created 2 played cards.  Boot up, comes online, insert ticket, long pause, spits ticket out.

Add some bonus credits using the WebUI and/or the RFID card, play a bit, hit cash out, long pause, hand pay.

Here are the logs collected from serial.....

**Ticket in**
```
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 67
Unable to read data - timeout
Redeeming ticket
SAS Event Received: 51
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
```

**Ticket Out**
```
Arduino TITO and Player Tracking - Version 2.0 (Dec 22, 2020) By Marc R. Davis
Initializing...
IP address: 192.168.254.99
Initialization complete
Card Inserted
Card ID: 5727C4A6
Card Type: Player
Cardholder: Player1
Player Stats - Games played: 2 Games Won: 2 Games Lost: 0 Total Won: 2600
Reading meters from game
Unable to read data - timeout
Unable to read data - timeout
Unable to read data - timeout
Unable to read data - timeout
Unable to read data - timeout
Unable to read data - timeout
Could not read current stats from game. Player's current session will not be saved.
Ready for play
SAS Event Received: 51
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 1F
SAS Event Received: 66
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 57
Unable to read data - timeout
Printing cashout ticket
SAS Event Received: 51
SAS Event Received: 51
SAS Event Received: 51
```

**Comment by marcrdavis** [comment]
Hi. Double check your Tito settings in the game to my instructions. It’s looks like something is wrong with the coms channel or the serial interface is having problems.  

Also... what kind of game and software are you running?

Marc

**Comment by marcrdavis** [comment]
Took a look at the code and the log you sent; your machine is sending 1F – that is an unexpected (and possibly invalid) value). Normally the active SAS serial channel puts out a ‘heartbeat’ consisting of 0x80 and 0x81, yours seems to be sending 1F – which is not a valid response. A Long Poll of 01,1F by the host would cause the game to return the version number. But I don’t implement that in my code.

 

I think that the serial channel may be wrong. On Step 4A on Page 5 of the doc make sure the SAS channel is set to 3 and then in step 7A make sure it is set to 1. Then – goto the Diagnostics menu on the machine, open the Comm Channel Analyzer, select Com 3 and look at the data – at idle it should be series of 0x80 and 0x81 … send me a screen shot of what you are seeing there.

 

Marc

**Comment by Eddiiie** [comment]
Hi,
My SASHost setup is on COM1.
![G20-SAS2](https://user-images.githubusercontent.com/10628416/103450560-2e7ca900-4c6d-11eb-9eee-9891667dd983.jpg)
![G20-SAS8](https://user-images.githubusercontent.com/10628416/103450679-98498280-4c6e-11eb-8077-2f1741020021.jpg)

On an AVP you have these daughter cards..  Fibre, RS232, Data Collection, etc.  I have my RS232 board in the slot for COM1.  Is the data exchanged different depending on which port it is coming from?    BettorTITO doesn't seem to care.

Could it be related to time?  There is a note in red that says the Protocol controlling Voucher In/Out will also control clock.

Here are some more screenshots -
![G20-SAS3](https://user-images.githubusercontent.com/10628416/103450604-ca0e1980-4c6d-11eb-8513-9c734616227d.jpg)
![G20-SAS5](https://user-images.githubusercontent.com/10628416/103450659-5ae4f500-4c6e-11eb-8fd7-f174297a4159.jpg)
![G20-SAS7](https://user-images.githubusercontent.com/10628416/103450669-6b956b00-4c6e-11eb-91db-5904c3cf891f.jpg)
![G20-SAS6](https://user-images.githubusercontent.com/10628416/103450675-8962d000-4c6e-11eb-9f58-5b8d44601a50.jpg)
![G20-SAS4](https://user-images.githubusercontent.com/10628416/103450692-c3cc6d00-4c6e-11eb-937d-ca2c215dae63.jpg)

Granted, there are a couple settings that are not set according to your recommendations.  Such as Progressive (Link 7 is not an option), 

Is there a NOOP or something the program can respond to when it gets 1F?       If it was a communication issue wouldnt the other options not work?

**Comment by marcrdavis** [comment]
Hi – I have not tested this on an AVP system or anything other than COM 3 – it is based on the same ports as the BETTORSlots board. Can you change your SAS port to COMM3?

 

Also – what type of game is this? It might help me understand what is going on. Thx

 

Marc

**Comment by marcrdavis** [comment]
Well com1 may be correct; is everything setup as in this video: https://www.youtube.com/watch?v=JKjyeFQPltA

**Comment by Eddiiie** [comment]
I moved to COM3.   In doing so I noticed one of the pins loose on the Serial adapter.   Fixed it and the 1F and 51 61 stuff has gone away.  In fact, the serial monitor window is pretty quiet after initializing and stuff.   

Unfortunately, TITO is still not working.
 I swear I'd see a message about validating when inserting a ticket before..?  Now there is nothing.

Looking at the communication output in diagnostics, RX is 80, 81   TX is 0.  Most of the time.    I can't insert a ticket of course.
I DO have a serial port tapper to listen in on the conversation. 

Also have WMS and Konami can test on.    It would be easier to move it to the other machines first.

**Comment by Eddiiie** [comment]
Yes, everything is setup according to that video.  I can plug the BettorTITO in and TITO works fine.
The machine was setup with BettorTITO before plugging in the ArduinoTITO-PlayerTracking system.  

Not sure if I mentioned I went back to COMM1 after testing COMM3.

Lemme try a couple other machines that are setup for BettorTITO in a few.

**Comment by Eddiiie** [comment]
Hmmm Same thing on the Konami.
Everything seems to work except TITO.
I will experiment more tomorrow.

Did not test WMS

**Comment by marcrdavis** [comment]
The RX is 80, 81 TX 0 is the normal idle state of the comm channel - so that’s good. The serial log on my app should be quiet except for when exceptions are thrown or long poll responses. The Tito commands are well documented and should work fine on your system. You say the other commands are working so that’s good. 

This serial tap? What is that? Can you remove it?

**Comment by Eddiiie** [comment]
The serial tap is not connected.  Was just offering that up if we wanted to capture a ticket insert event and see what is going over the wire.

Will make a new board with TITO Only set to 1 tomorrow.

Where are the tito commands well documented?


Here is the tap -
[Serial Tap](https://www.amazon.com/Black-2-Port-RS232-Passive-Splitter/dp/B00AO9C38E/ref=pd_sbs_147_6/145-9944505-1483029?_encoding=UTF8&pd_rd_i=B00AO9C38E&pd_rd_r=6bc4d120-9c58-4901-b836-941943c0a5f4&pd_rd_w=xHDWD&pd_rd_wg=Y4UaF&pf_rd_p=ed1e2146-ecfe-435e-b3b5-d79fa072fd58&pf_rd_r=YPZWBT2M980ZVGFSQR92&psc=1&refRID=YPZWBT2M980ZVGFSQR92
)

**Comment by marcrdavis** [comment]
If you can capture the ticket in and ticket out data using the working Tito board and send it to me that would be extremely helpful.

**Comment by Eddiiie** [comment]
Some IO Diag screenshots...
![IO1](https://user-images.githubusercontent.com/10628416/103452079-7953ec00-4c80-11eb-9b96-55c510a5701b.jpg)
![IO2](https://user-images.githubusercontent.com/10628416/103452083-7bb64600-4c80-11eb-89c4-5fc0290b0399.jpg)
![IO3](https://user-images.githubusercontent.com/10628416/103452085-7eb13680-4c80-11eb-9385-80a0ade6cc69.jpg)
![IO4](https://user-images.githubusercontent.com/10628416/103452088-81139080-4c80-11eb-8b2b-4b3150b710e2.jpg)
![IO5](https://user-images.githubusercontent.com/10628416/103452089-82dd5400-4c80-11eb-8a60-607152a21cf0.jpg)

**Comment by Eddiiie** [comment]
Will grab capture if Ticket In and Out of working tomorrow.
Thank you for your support!!

**Comment by marcrdavis** [comment]
Make sure your config is back on COM1 – that appears to be the serial port on the AVP (S2000/GameKings use COM3)

**Comment by marcrdavis** [comment]
https://studylib.net/doc/25224123/sas-602-protocol-manual

Section 15.7 for the cashout process

**Comment by marcrdavis** [comment]
I have a theory as to why just the TITO is not working; send me your email address – I want to forward you a newer version of the code for testing. Thanks!

 

Marc
