### ISSUE TITLE
i think here may be wrong.

### ISSUE THREAD

**Issue by shownb** [marcrdavis/ArduinoTITO-PlayerTracking#4]
https://github.com/marcrdavis/ArduinoTITO-PlayerTracking/blob/c24fe7dce08bed3b15fd8b20e81484e8756b06f4/AruinoTITO/src/ArduinoTITO/ArduinoTITO.ino#L289

and can i contact with you to ask some question?

**Comment by marcrdavis** [comment]
Sorry - just seeing this now; what seems to be the issue?

**Comment by shownb** [comment]
> Sorry - just seeing this now; what seems to be the issue?

    TRS [4] = TEQ [14];                          // Ticket Amount BCD1  LSB
    TRS [5] = TEQ [15];                          // Ticket Amount BCD2
    TRS [6] = TEQ [16];                          // Ticket Amount BCD3
    TRS [7] = TEQ [17];                          // Ticket Amount BCD4
    TRS [8] = TEQ [18];                          // Ticket Amount BCD5  MSB
    TRS [9] = 0x00;                              // Parsing Code
    TRS [10] = TEQ [10];                         // Validation BCD1
    TRS [11] = TEQ [11];                         // Validation BCD2
    TRS [12] = TEQ [12];                         // Validation BCD3
    TRS [13] = TEQ [13];                         // Validation BCD4
    TRS [14] = TEQ [14];                         // Validation BCD5
    TRS [15] = TEQ [15];                         // Validation BCD6
    TRS [16] = TEQ [16];                         // Validation BCD7
    TRS [17] = TEQ [17];                         // Validation BCD8
    TRS [18] = TEQ [18];                         // Validation BCD9

should be 
    TRS [4] = TEQ [4];                          // Ticket Amount BCD1  LSB
    TRS [5] = TEQ [5];                          // Ticket Amount BCD2
    TRS [6] = TEQ [6];                          // Ticket Amount BCD3
    TRS [7] = TEQ [7];                          // Ticket Amount BCD4
    TRS [8] = TEQ [8];                          // Ticket Amount BCD5  MSB

**Comment by marcrdavis** [comment]
In a casino setting - using SAS Validation or Enhanced Validation you would be correct. For the local (or Arduino) system validation we use the validation code as the ticket amount (they are the same). This code has been tested and works as expected.
