### ISSUE TITLE
Qué tal si tratamos de este proyecto adaptarlo a una esp32?

### ISSUE THREAD

**Issue by juanclavel** [marcrdavis/ArduinoTITO-PlayerTracking#7]

**Comment by marcrdavis** [comment]
I am considering it.

**Comment by juanclavel** [comment]
thank you very much it would be easier to carry out this excellent project

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: marcrdavis ***@***.***>
Enviado: Monday, November 14, 2022 8:24:17 PM
Para: marcrdavis/ArduinoTITO-PlayerTracking ***@***.***>
Cc: juanclavel ***@***.***>; Author ***@***.***>
Asunto: Re: [marcrdavis/ArduinoTITO-PlayerTracking] Qué tal si tratamos de este proyecto adaptarlo a una esp32? (Issue #7)


I am considering it.
