### ISSUE TITLE
SAS adapter?

### ISSUE THREAD

**Issue by philfry9** [marcrdavis/ArduinoTITO-PlayerTracking#8]
Hi Marc,

Thanks for sharing this project. I just acquired my first machine and am in the process of getting this setup now.
I think I have everything set with one exception. The machine did not have BS-TITO previously. I have the recommended serial connector connected to the Arduino. I would like to build an adapter from the serial output of the Arduino (RS232 to TTL Converter Module COM Serial Port Board) into the SAS port on the comms panel. I have looked t the schematics for that port (from NLG forums) but cannot seem to get a proper connection from the Arduino system to the comms panel to receive inputs.

Any chance you could provide a quick wiring/pinout explanation for my to build a connection from the serial expansion board to the SAS port? Eg: Can I wire from the 5-pin SAS into the serial port directly?

Appreciate any help.

<img width="327" alt="Screenshot 2023-02-27 at 6 53 29 PM" src="https://user-images.githubusercontent.com/30012269/221724238-6644cc11-424e-4184-ae7b-baad939a7f3f.png">

**Comment by philfry9** [comment]
Thought to look at the pinout for RS232 protocol. Going to try matching this....
![rs232-pinout](https://user-images.githubusercontent.com/30012269/221737797-00d6707c-1e1f-4b71-9eb3-d47cabe44877.jpg)

**Comment by marcrdavis** [comment]
Hi Phillip,

 

Thanks for writing. I am a little confused, I think what you are looking to do is documented on page 22 of the manual. It describes the pinout of the J82 connector on the IGT S2000/GameKing and how to wire it to a 9-pin male serial connection using a DB9 to Dupont Serial cable: https://www.amazon.com/gp/product/B081GJR1MN

 

Please take a look at let me know if that is what you needed.

 

Marc

 

From: Phillip F ***@***.*** 
Sent: Monday, February 27, 2023 7:58 PM
To: marcrdavis/ArduinoTITO-PlayerTracking ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [marcrdavis/ArduinoTITO-PlayerTracking] SAS adapter? (Issue #8)

 

Hi Marc,

Thanks for sharing this project. I just acquired my first machine and am in the process of getting this setup now.
I think I have everything set with one exception. The machine did not have BS-TITO previously. I have the recommended serial connector connected to the Arduino. I would like to build an adapter from the serial output of the Arduino (RS232 to TTL Converter Module COM Serial Port Board) into the SAS port on the comms panel. I have looked t the schematics for that port (from NLG forums) but cannot seem to get a proper connection from the Arduino system to the comms panel to receive inputs.

Any chance you could provide a quick wiring/pinout explanation for my to build a connection from the serial expansion board to the SAS port? Eg: Can I wire from the 5-pin SAS into the serial port directly?

Appreciate any help.

 <https://user-images.githubusercontent.com/30012269/221724238-6644cc11-424e-4184-ae7b-baad939a7f3f.png>

**Comment by philfry9** [comment]
Absolutely correct. I have read that manual probably 5 times and have no idea how I missed it. Much appreciated!
